---
title: "GitHub 101: A Brief Introduction"
format:
  html:
    page-layout: full
---

# Présentation du workshop

Dans cet atelier, nous explorerons les fondamentaux de GitHub, une plateforme essentielle pour la collaboration et la gestion de projets logiciels. Destiné aux débutants, cet atelier vous guidera à travers les concepts clés de Git et GitHub, y compris la création et la gestion de dépôts, le suivi des modifications de code, l'utilisation des branches, la gestion des pull requests et la résolution des conflits. Vous apprendrez également à naviguer dans l'interface GitHub, à collaborer avec d'autres développeurs et à exploiter les fonctionnalités avancées pour optimiser votre flux de travail. Que vous soyez un développeur novice ou simplement curieux d'en savoir plus sur cette plateforme incontournable, cet atelier vous fournira les compétences nécessaires pour démarrer avec GitHub et améliorer votre productivité dans le développement logiciel.

# Premières étapes

## Création de votre compte

Créer votre compte personnel sur [***GitHub***](https://github.com/) et vérifier subséquemment votre adresse mail.

## Installation

